name: ttpos

packages:
  - apps/pos
  - apps/tablet
  - apps/kds
  - apps/assistant
  - apps/mobile
  - apps/menu
  - packages/server
  - packages/shared
  - packages/ui
  - packages/dotenv
  - packages/logger
  - packages/i18n
  - packages/api
  - packages/model
  - packages/flutter_subscreen_plugin

scripts:
  lint:
    run: melos run analyze && melos run format
    description: 运行所有包的分析和格式化

  format:
    run: |
      dart format \
        --line-length 120 \
        --output=write \
        .
    description: 运行所有包的格式化

  analyze:
    run: |
      melos exec -c 5 -- \
        dart analyze . --fatal-infos
    description: 运行所有包的分析

  prisma:generate:
    exec: npx prisma generate
    description: 在server包中执行npx prisma generate命令
    packageFilters:
      scope: server

  prisma:migrate:dev:
    exec: npx prisma migrate dev
    description: 在server包中执行npx prisma migrate dev命令
    packageFilters:
      scope: server

  sort:
    exec: dart pub run import_sorter:main
    description: 在所有包中执行dart pub run import_sorter:main命令
    packageFilters:
      scope:
        - pos
        - assistant
        - tablet
        - kds
        - mobile
        - menu

  init:
    description: 初始化所有App包的环境变量文件
    run: |
      sh ./scripts/env_file.sh

  update:version:
    run: sh ./scripts/update_version.sh
    description: 更新所有包的版本号

  translate:
    run: bash ./scripts/translate.sh
    description: 翻译指令

  build:pos:android:
    run: sh ./scripts/build_android.sh pos

  build:tablet:android:
    run: sh ./scripts/build_android.sh tablet

  build:assistant:android:
    run: sh ./scripts/build_android.sh assistant

  build:kds:android:
    run: sh ./scripts/build_android.sh kds

  build:android:
    run: sh ./scripts/build_android.sh

  # mac 构建
  pack:pos:mac:
    run: sh ./scripts/pack_mac.sh pos

  pack:tablet:mac:
    run: sh ./scripts/pack_mac.sh tablet

  pack:assistant:mac:
    run: sh ./scripts/pack_mac.sh assistant

  pack:kds:mac:
    run: sh ./scripts/pack_mac.sh kds

  build:mac:
    exec: |
      flutter build macos --dart-define-from-file=.env.production.local
      mkdir -p ../../releases/MELOS_PACKAGE_NAME/MELOS_PACKAGE_VERSION
    description: 在所有包中执行flutter build macos --dart-define-from-file=.env.production.local命令
    packageFilters:
      scope:
        - pos
        - assistant
        - tablet
        - kds

  build:mobile:web:
    run: sh ./scripts/build_web.sh mobile

  build:menu:web:
    run: sh ./scripts/build_web.sh menu

  build:web:
    run: sh ./scripts/build_web.sh

  build:win:
    exec: pwsh -File ..\..\scripts\build_win.ps1
    description: 在所有包中执行 Windows 构建
    packageFilters:
      scope:
        - pos
        - assistant
        - tablet
        - kds

  setup_env:
    run: sh ./scripts/setup_env.sh

command:
  clean:
    hooks:
      post: sh ./scripts/clean.sh

  bootstrap:
    # 初始化环境变量文件
    hooks:
      post: sh ./scripts/env_file.sh

    # 共用的依赖
    dependencies:
      # 核心依赖
      get: ^4.6.6

      # 网络相关
      dio: ^5.7.0
      connectivity_plus: ^6.1.1
      web_socket_client: ^0.2.0

      # 存储相关
      shared_preferences: ^2.3.4
      flutter_secure_storage: ^9.2.4
      path: ^1.9.0
      path_provider: ^2.1.5

      # UI 相关
      bot_toast: ^4.1.3
      flutter_dotenv: ^5.2.1

      # 工具类
      uuid: ^4.4.2
      encrypt: ^5.0.3
      crypto: ^3.0.6
      intl: ^0.19.0
      collection: ^1.19.0
      logging: ^1.3.0
      decimal: ^3.0.2
      sentry_flutter: ^8.14.1
      window_manager: ^0.4.3

      # PDF 相关
      pdf: ^3.11.1
      pdfx: ^2.8.0

      # 其他
      plugin_platform_interface: ^2.0.2
      timezone: ^0.10.0
      dart_mq: ^1.1.0
      wakelock_plus: ^1.3.2

    # 开发依赖
    dev_dependencies:
      # Lints
      flutter_lints: ^5.0.0
      lints: ^5.0.0

      # 代码生成
      build_runner: ^2.4.14
      freezed: ^2.5.7
      json_serializable: ^6.9.0

      # 其他工具
      import_sorter: ^4.6.0
      change_app_package_name: ^1.4.0
      flutter_launcher_icons: ^0.14.3
      rename_app: ^1.6.3

    # 依赖覆盖
    dependencyOverrides:
      ttpos_model: ^0.0.1
      ttpos_api: ^0.0.1
      ttpos_shared: ^0.0.1
      ttpos_ui: ^0.0.1
      ttpos_logger: ^0.0.1
      ttpos_i18n: ^0.0.1
      ttpos_dotenv: ^0.0.1
      ttpos_flutter_subscreen_plugin: ^0.0.1
